# Generated by Django 3.2.12 on 2024-01-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20240106_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_tags',
            field=models.CharField(blank=True, choices=[('Food', 'Food'), ('Tech', 'Tech'), ('Random', 'Random'), ('IRL', 'IRL')], max_length=15, null=True),
        ),
    ]
